
import { Book } from '@/types/book';

export const MOCK_BOOK_ID = '504';

export const MOCK_BOOK_DATA: Book = {
  id: Number(MOCK_BOOK_ID),
  bookName: 504,
  titleFa: '۵۰۴ واژه',
  titleEn: '504 Essential Words',
  subTitleFa: 'کتاب ضروری برای یادگیری لغات',
  subTitleEn: 'Essential book for vocabulary learning',
  image: 'https://i.postimg.cc/qRJ6d5qM/504-absolute-essential-words.jpg',
  link: '', // Mock download
  lessonWordCount: '12',
  isLock: false,
  bookSize: 5000000,
  ItemType: 'Book',
  keyBook: '504',
  version: '1',
  contentType: 'Text',
  isNewVersion: 'false',
  helpTitleFa: '',
  helpTitleEn: '',
  helpDescriptionFa: '',
  helpDescriptionEn: '',
  order: 1,
  bgColor: '#FFCC00',
  isSuggestion: false
};

const lesson1Words = [
  {
    wordID: '1-1',
    word: 'Abandon',
    trans: 'ترک کردن، رها کردن',
    phonetic: 'uk /əˈbæn.dən/ us /əˈbæn.dən/',
    exam1: 'When Roy abandoned his family, the police went looking for him.',
    examTrans1: 'وقتی ”روی” خانواده‌اش را ترک کرد، پلیس به جستجویش پرداخت.',
    def: 'Desert; leave without planning to come back; quit',
    exam2: 'The soldier could not abandon his friends who were hurt in battle.',
    examTrans2: 'سرباز نتوانست دوستانش را که در جنگ آسیب دیده بودند ترک کند.',
    exam3: 'Because Rose was poor, she had to abandon her idea of going to college.',
    examTrans3: 'چون ”رز” فقیر بود، مجبور شد از فکر رفتن به دانشگاه دست بکشد.',
    lessonId: 1
  },
  {
    wordID: '1-2',
    word: 'Keen',
    trans: 'تیز، زیرک، مشتاق',
    phonetic: 'uk /kiːn/ us /kiːn/',
    exam1: "The butcher's keen knife cut through the meat.",
    examTrans1: 'چاقوی تیز قصاب گوشت را قطعه قطعه کرد.',
    def: 'Sharp; eager; intense; sensitive',
    exam2: 'My dog has a keen sense of smell.',
    examTrans2: 'سگ من حس بویایی قوی دارد.',
    exam3: "Bill's keen mind pleased all his teachers.",
    examTrans3: 'ذهن زیرک بیل معلمانش را راضی کرد.',
    lessonId: 1
  },
  {
    wordID: '1-3',
    word: 'Jealous',
    trans: 'حسود',
    phonetic: 'uk /ˈdʒel.əs/ us /ˈdʒel.əs/',
    exam1: 'A detective was hired by the jealous widow to find the boyfriend who had abandoned her.',
    examTrans1: 'بیوه زن حسود کارآگاهی را استخدام کرد تا دوست پسری را که او را ترک کرده بود پیدا کند.',
    def: 'Afraid that the one you love might prefer someone else; wanting what someone else has',
    exam2: 'Although my neighbor just bought a new car, I am not jealous of him.',
    examTrans2: 'با اینکه همسایه‌ام به تازگی ماشین جدیدی خریده است، به او حسادت نمی‌کنم.',
    exam3: 'Being jealous, Mona would not let her boyfriend dance with any of the cheerleaders.',
    examTrans3: 'از آنجا که مونا حسود بود، اجازه نمی‌داد دوست پسرش با هیچ‌کدام از تشویق‌کنندگان برقصد.',
    lessonId: 1
  },
  {
    wordID: '1-4',
    word: 'Tact',
    trans: 'تدبیر، نزاکت، ظرافت',
    phonetic: 'uk /tækt/ us /tækt/',
    exam1: "My aunt never hurts anyone's feelings because she always uses tact.",
    examTrans1: 'خاله ام هرگز احساسات کسی را جریحه دار نمی کند زیرا او همیشه با نزاکت رفتار می‌کند.',
    def: 'Ability to say the right thing',
    exam2: 'By the use of tact, Janet was able to calm her jealous husband.',
    examTrans2: 'ژانت توانست با استفاده از تدبیر، شوهر حسودش را آرام کند.',
    exam3: 'Your friends will admire you if you use tact and thoughtfulness.',
    examTrans3: 'اگر با تدبیر و ملاحظه رفتار کنید، دوستانتان شما را تحسین خواهند کرد.',
    lessonId: 1
  },
  {
    wordID: '1-5',
    word: 'Oath',
    trans: 'قسم، سوگند',
    phonetic: 'uk /əʊθ/ us /oʊθ/',
    exam1: 'The president will take the oath of office tomorrow',
    examTrans1: 'فردا رئیس جمهور سوگند اداری یاد می‌کند.',
    def: 'A promise that something is true; a curse',
    exam2: 'In court, the witness took an oath that he would tell the whole truth.',
    examTrans2: 'در دادگاه، شاهد سوگند یاد کرد که تمام حقیقت را بگوید.',
    exam3: 'When Terry discovered that he had been abandoned, he let out an angry oath.',
    examTrans3: 'وقتی تری فهمید که رها شده است، از روی عصبانیت فحش داد.',
    lessonId: 1
  },
  {
    wordID: '1-6',
    word: 'Vacant',
    trans: 'خالی',
    phonetic: 'uk /ˈveɪ.kənt/ us /ˈveɪ.kənt/',
    exam1: 'Someone is planning to build a house on that vacant lot',
    examTrans1: 'کسی قصد دارد روی آن قطعه زمین خالی خانه بسازد.',
    def: 'Empty; not filled',
    exam2: 'I put my coat on that vacant seat.',
    examTrans2: 'من کتم را روی صندلی خالی گذاشتم.',
    exam3: 'When the landlord broke in, he found that apartment vacant.',
    examTrans3: 'وقتی صاحب خانه وارد شد، متوجه شد که آپارتمان خالی است.',
    lessonId: 1
  },
  {
    wordID: '1-7',
    word: 'Hardship',
    trans: 'بی نوایی، محنت، سختی',
    phonetic: 'uk /ˈhɑːd.ʃɪp/ us /ˈhɑːrd.ʃɪp/',
    exam1: 'The fighter had to face many hardships before he became champion.',
    examTrans1: 'جنگجو پیش از آنکه قهرمان شود مجبور بود با سختی‌های زیادی مواجه شود.',
    def: 'Something that is hard to bear; difficulty',
    exam2: 'Abe Lincoln was able to overcome one hardship after another.',
    examTrans2: 'آبراهام لینکلن قادر بود مشکلات را یکی پس از دیگری از میان بردارد.',
    exam3: 'On account of hardship, Bert was let out of the army to take care of his sick mother.',
    examTrans3: 'برت به دلیل مشکلاتش اجازه یافت ارتش را ترک کند تا از مادر بیمارش مراقبت نماید.',
    lessonId: 1
  },
  {
    wordID: '1-8',
    word: 'Gallant',
    trans: 'شجاع',
    phonetic: 'uk /ˈɡæl.ənt/ us /ˈɡæl.ənt/ /ɡəˈlænt/ /ɡəˈlɑːnt/',
    exam1: 'The pilot swore a gallant oath to save his buddy.',
    examTrans1: 'خلبان سوگند شجاعانه یاد کرد که دوستش را نجات دهد.',
    def: 'Brave; showing respect for women',
    exam2: 'Many gallant knights entered the contest to win the princess.',
    examTrans2: 'شوالیه های شجاع بسیاری برای به دست آوردن شاهزاده خانم وارد مسابقه شدند.',
    exam3: 'Ed is so gallant that he always gives up his subway seat to a woman.',
    examTrans3: 'اد آنقدر با جوانمرد است که همیشه جایش را در مترو به یک خانم می‌دهد.',
    lessonId: 1
  },
  {
    wordID: '1-9',
    word: 'Data',
    trans: 'اطلاعات، داده‌ها',
    phonetic: 'uk /ˈdeɪ.tə/ us /ˈdeɪ.t̬ə/ /dæt̬.ə/',
    exam1: 'The data about the bank robbery were given to the F.B.I.',
    examTrans1: 'شواهد مربوط به سرقت بانک به اف.بی.آی. داده شد.',
    def: "Facts; information (technically plural, singular form is 'datum')",
    exam2: 'After studying the data, we were able to finish our report.',
    examTrans2: 'پس از بررسی اطلاعات، توانستیم گزارش خود را تمام کنیم.',
    exam3: 'Unless you are given all the data, you cannot do the math problem.',
    examTrans3: 'اگر همه داده‌ها را نداشته باشید، نمی‌توانید مسئله ریاضی را حل کنید.',
    lessonId: 1
  },
  {
    wordID: '1-10',
    word: 'Unaccustomed',
    trans: 'ناآشنا',
    phonetic: 'uk /ˌʌn.əˈkʌs.təmd/ us /ˌʌn.əˈkʌs.təmd/',
    exam1: "Coming from Alaska, Claud was unaccustomed to Florida's heat.",
    examTrans1: 'چون کلود اهل آلاسکا بود، به گرمای فلوریدا عادت نداشت.',
    def: 'Not used to something',
    exam2: 'The king was unaccustomed to having people disobey him.',
    examTrans2: 'پادشاه به اطاعت نکردن مردم از خودش عادت نداشت.',
    exam3: 'Unaccustomed as he was to exercise, Vic quickly became tired.',
    examTrans3: 'ویک که به ورزش عادت نداشت، خیلی زود خسته شد.',
    lessonId: 1
  },
  {
    wordID: '1-11',
    word: 'Bachelor',
    trans: 'مرد مجرد، لیسانس',
    phonetic: 'uk /ˈbætʃ.əl.ər/ us /ˈbætʃ.əl.ɚ/',
    exam1: 'My brother took an oath to remain a bachelor.',
    examTrans1: 'برادرم قسم خورد که مجرد باقی بماند.',
    def: "A man who has not married, bachelor's degree",
    exam2: 'In the movie, the married man was mistaken for a bachelor.',
    examTrans2: 'در این فیلم، مرد متاهل با یک مرد مجرد اشتباه گرفته شد.',
    exam3: 'Before the wedding, all his bachelor friends had a party.',
    examTrans3: 'قبل از عروسی، تمام دوستان مجردش یک مهمانی گرفتند.',
    lessonId: 1
  },
  {
    wordID: '1-12',
    word: 'Qualify',
    trans: 'واجد شرایط شدن',
    phonetic: 'uk /ˈkwɒl.ɪ.faɪ/ us /ˈkwɑː.lə.faɪ/',
    exam1: 'I am trying to qualify for the job which is now vacant.',
    examTrans1: 'سعی می‌کنم برای شغلی که اکنون خالی است، واجد شرایط شوم.',
    def: 'Become fit; show that you are able',
    exam2: "Since Pauline can't carry a tune, she is sure that she will never qualify for the Girls' Chorus.",
    examTrans2: 'از آنجا که پائولین نمی‌تواند به درستی آواز بخواند، مطمئن است که هرگز صلاحیت حضور در گروه کُر دختران را پیدا نخواهد کرد.',
    exam3: "You have to be over 5'5\" to qualify as a policeman in our town.",
    examTrans3: 'قد شما باید بیشتر از ۵ فوت و ۵ اینچ باشد تا برای پلیس شدن در شهر ما واجد شرایط شوید.',
    lessonId: 1
  }
];

const lesson2Words = [
  {
    wordID: '1-13',
    word: 'Corpse',
    trans: 'جنازه، جسد',
    phonetic: 'uk /kɔːps/ us /kɔːrps/',
    exam1: 'When given all the data on the corpse, Columbo was able to solve the murder.',
    examTrans1: 'زمانی که تمامی حقایق درباره جسد مشخص شد، کلومبو توانست جنایت را کشف کند.',
    def: 'A dead body, usually of a person',
    exam2: 'The corpse was laid to rest in the vacant coffin.',
    examTrans2: 'جنازه در تابوت خالی آرام گرفت.',
    exam3: 'An oath of revenge was sworn over the corpse by his relatives.',
    examTrans3: 'خویشاوندان بالای سر جنازه سوگند یاد کردند که انتقام او را بگیرند.',
    lessonId: 2
  },
  {
    wordID: '2-1',
    word: 'Conceal',
    trans: 'پنهان کردن، پوشاندن',
    phonetic: 'uk /kənˈsiːl/ us /kənˈsiːl/',
    exam1: 'Chris could not conceal his love for Gloria.',
    examTrans1: 'کریس نمی‌توانست عشق خود به گلوریا را پنهان کند.',
    def: 'Hide',
    exam2: 'Count Dracula concealed the corpse in his castle.',
    examTrans2: 'کنت دراکولا جنازه را در قلعه‌ی خود پنهان کرد.',
    exam3: 'The money was so cleverly concealed that we were forced to abandon our search for it.',
    examTrans3: 'پول‌ها آنقدر ماهرانه پنهان شده بود که مجبور شدیم از جستجو دست بکشیم.',
    lessonId: 2
  },
  {
    wordID: '2-2',
    word: 'Dismal',
    trans: 'غم‌انگیز، دلتنگ‌کننده',
    phonetic: 'uk /ˈdɪz.məl/ us /ˈdɪz.məl/',
    exam1: 'When the weather is so dismal, I sometimes stay in bed all day.',
    examTrans1: 'زمانی که هوا اینقدر گرفته است، بعضی وقت‌ها تمام روز را در رختخواب می‌مانم.',
    def: 'Dark and depressing',
    exam2: 'I am unaccustomed to this dismal climate.',
    examTrans2: 'به این آب و هوای گرفته عادت ندارم.',
    exam3: "As the dismal reports of the election came in, the senator's friends tactfully made no mention of them.",
    examTrans3: 'هنگامی که گزارش‌های ناامیدکننده انتخابات رسید، دوستان سناتور با تدبیر هیچ اشاره‌ای به آنها نکردند.',
    lessonId: 2
  },
  {
    wordID: '2-3',
    word: 'Frigid',
    trans: 'خیلی سرد',
    phonetic: 'uk /ˈfrɪdʒ.ɪd/ us /ˈfrɪdʒ.ɪd/',
    exam1: 'It was a great hardship for the survivors to live through the frigid winter at Valley Forge.',
    examTrans1: 'برای بازماندگان، گذراندن زمستان سرد و سخت در ولی فورج یک مشقت بزرگ بود.',
    def: 'Very cold',
    exam2: 'The jealous bachelor was treated in a frigid manner by his girlfriend.',
    examTrans2: 'مرد مجرد حسود توسط دوست‌دخترش با او به سردی رفتار شد.',
    exam3: "Inside the butcher's freezer the temperature was frigid.",
    examTrans3: 'دمای داخل فریزر قصابی بسیار سرد بود.',
    lessonId: 2
  },
  {
    wordID: '2-4',
    word: 'Inhabit',
    trans: 'ساکن شدن، زیستن',
    phonetic: 'uk /ɪnˈhæb.ɪt/ us /ɪnˈhæb.ɪt/',
    exam1: 'Eskimos inhabit the frigid part of Alaska.',
    examTrans1: 'اسکیموها در منطقه قطبی آلاسکا زندگی می‌کنند.',
    def: 'Live in',
    exam2: 'Because Sidney qualified, he was allowed to inhabit the vacant apartment.',
    examTrans2: 'چون سیدنی واجد شرایط بود، اجازه یافت تا در آپارتمان خالی اقامت کند.',
    exam3: 'Many crimes are committed each year against those who inhabit the slum area of our city.',
    examTrans3: 'هر ساله جنایات بسیاری علیه کسانی که در مناطق زاغه‌نشین شهرمان سکونت دارند، رخ می‌دهد.',
    lessonId: 2
  },
  {
    wordID: '2-5',
    word: 'Numb',
    trans: 'بی حس',
    phonetic: 'uk /nʌm/ us /nʌm/',
    exam1: 'My fingers quickly became numb in the frigid room',
    examTrans1: 'انگشتانم در اتاق سرد به سرعت بی حس شدند.',
    def: 'Without the power of feeling; deadened',
    exam2: 'A numb feeling came over Mr. Massey as he read the telegram.',
    examTrans2: 'هنگامی که آقای ماسی تلگراف را می خواند، احساس بی حسی به او دست داد.',
    exam3: 'When the nurse stuck a pin in my numb leg, I felt nothing.',
    examTrans3: 'زمانی که پرستار یک سوزن را در پای بی حس من فرو کرد، هیچ چیز احساس نکردم.',
    lessonId: 2
  },
  {
    wordID: '2-6',
    word: 'Peril',
    trans: 'مخاطره، خطر',
    phonetic: 'uk /ˈper.əl/ us /ˈper.əl/',
    exam1: 'The hunter was abandoned by the natives when he described the peril which lay ahead of them.',
    examTrans1: 'زمانی که شکارچی خطری را که در پیش روی آنها بود توصیف کرد، بومی‌ها او را ترک کردند.',
    def: 'Danger',
    exam2: 'There is great peril in trying to climb the mountain.',
    examTrans2: 'تلاش برای بالا رفتن از کوه خطر زیادی دارد.',
    exam3: 'Our library is filled with stories of perilous adventures.',
    examTrans3: 'کتابخانه ما پر از داستان‌هایی درباره ماجراجویی‌های خطرناک است.',
    lessonId: 2
  },
  {
    wordID: '2-7',
    word: 'Recline',
    trans: 'تکیه دادن، لم دادن، دراز کشیدن',
    phonetic: 'uk /rɪˈklaɪn/ us /rɪˈklaɪn/',
    exam1: 'Richard likes to recline in front of the television set.',
    examTrans1: 'ریچارد دوست دارد جلوی تلویزیون لم بدهد.',
    def: 'Lie down; stretch out; lean back',
    exam2: 'After reclining on her right arm for an hour, Maxine found that it had become numb.',
    examTrans2: 'بعد از اینکه ماکسین یک ساعت روی بازوی راستش لم داد، متوجه شد بازویش بی حس شده است.',
    exam3: "My dog's greatest pleasure is to recline by the warm fireplace.",
    examTrans3: 'بزرگترین لذت سگ من لم دادن کنار شومینه گرم است.',
    lessonId: 2
  },
  {
    wordID: '2-8',
    word: 'Shriek',
    trans: 'جیغ کشیدن',
    phonetic: 'uk /ʃriːk/ us /ʃriːk/',
    exam1: 'The maid shrieked when she discovered the corpse.',
    examTrans1: 'وقتی خدمتکار جسد را پیدا کرد، جیغ کشید.',
    def: 'Scream',
    exam2: 'With a loud shriek, Ronald fled from the room.',
    examTrans2: 'با یک جیغ بلند، رونالد از اتاق فرار کرد.',
    exam3: 'Facing the peril of the waterfall, the boatman let out a terrible shriek.',
    examTrans3: 'با دیدن خطر آبشار، قایقران جیغ وحشتناکی کشید.',
        lessonId: 2
  },
  {
    wordID: '2-9',
    word: 'Sinister',
    trans: 'شیطانی',
    phonetic: 'uk /ˈsɪn.ɪ.stər/ us /ˈsɪn.ə.stɚ/',
    exam1: 'The sinister plot to cheat the widow was uncovered by the police.',
    examTrans1: 'نقشه‌ی شوم برای فریب بیوه توسط پلیس فاش شد.',
    def: 'Evil; wicked; dishonest; frightening',
    exam2: 'When the bank guard spied the sinister-looking customer, he drew his gun.',
    examTrans2: 'زمانیکه نگهبان بانک متوجه مشتری شرور با ظاهر مشکوک شد، اسلحه اش را کشید.',
    exam3: 'I was frightened by the sinister shadow at the bottom of the stairs.',
    examTrans3: 'سایه شوم در انتهای راه پله مرا ترساند.',
    lessonId: 2
  }
];

export const MOCK_LESSONS = [
  {
    id: 1,
    lessonTitle: 'Lesson 1',
    listWord: lesson1Words
  },
  {
    id: 2,
    lessonTitle: 'Lesson 2',
    listWord: lesson2Words
  }
];
